# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

import aiohttp
from typing import List, Dict, Optional

from langbot_plugin.api.definition.components.common.event_listener import EventListener
from langbot_plugin.api.entities import events, context
from langbot_plugin.api.entities.builtin.platform import message as platform_message
from langbot_plugin.api.entities.builtin.provider import message as provider_message

from utils.forward_message import ForwardMessageSender

class DefaultEventListener(EventListener):

    async def initialize(self):
        await super().initialize()
        self.trigger_keyword = "盘搜"

        # 获取插件配置
        config = self.plugin.get_config()
        self.count_limit = config.get("count_limit", 5)
        self.pansou_api_url = config.get("pansouapi", "http://127.0.0.1:8888")
        self.onebot_http_url = config.get("onebot_http_url", "http://127.0.0.1:3000")
        self.onebot_access_token = config.get("onebot_access_token", "")

        # ==================== 新增配置 ====================
        self.default_cloud_types = config.get("default_cloud_types", "quark")
        self.enable_user_select = config.get("enable_user_select", False)
        # =================================================

        # 初始化合并转发消息发送器
        self.forward_sender = ForwardMessageSender(
            http_url=self.onebot_http_url,
            access_token=self.onebot_access_token if self.onebot_access_token else None
        )

        @self.handler(events.PersonMessageReceived)
        @self.handler(events.GroupMessageReceived)
        async def handle_search_request(event_context: context.EventContext):
            """处理用户搜索请求"""
            message_chain = event_context.event.message_chain
            user_text = self.get_user_text(message_chain)

            if not user_text.startswith(self.trigger_keyword):
                return

            # 提取搜索关键词
            keyword = user_text[len(self.trigger_keyword):].strip()
            if not keyword:
                await self.send_reply(event_context, "请输入搜索关键词，例如：盘搜 电影名")
                return

            # ==================== 新增：支持指定网盘 + 默认夸克 ====================
            cloud_types = None
            search_keyword = keyword
            if self.enable_user_select:
                cloud_types = None  # 全部资源模式
            else:
                # 支持命令末尾加类型：盘搜 蜡笔小新 夸克 / 全部 / 阿里云 等
                parts = keyword.rsplit(maxsplit=1)
                if len(parts) == 2:
                    possible_type = parts[1].strip().lower()
                    type_map = {
                        "夸克": "quark", "quark": "quark", "q": "quark",
                        "阿里云": "aliyun", "aliyun": "aliyun", "ali": "aliyun",
                        "百度": "baidu", "baidu": "baidu",
                        "全部": "all", "all": "all",
                    }
                    if possible_type in type_map:
                        mapped = type_map[possible_type]
                        cloud_types = None if mapped == "all" else [mapped]
                        search_keyword = parts[0].strip()
                    else:
                        cloud_types = [self.default_cloud_types] if self.default_cloud_types else None
                else:
                    cloud_types = [self.default_cloud_types] if self.default_cloud_types else None
            # =================================================

            # 发送搜索中提示
            await self.send_reply(event_context, f"正在搜索：{search_keyword}...")

            # 调用 PanSou API 搜索（支持 cloud_types 参数）
            results = await self.search_pansou(search_keyword, cloud_types)

            if not results:
                await self.send_reply(event_context, f"未找到与 \"{search_keyword}\" 相关的网盘资源")
                return

            # 构建合并转发消息并发送
            await self.send_forward_results(event_context, search_keyword, results)

            # 阻止事件继续传播
            event_context.prevent_default()

    def get_user_text(self, message_chain) -> str:
        """从消息链中提取纯文本内容"""
        text_parts = []
        for msg in message_chain:
            if hasattr(msg, 'text'):
                text_parts.append(msg.text)
            elif isinstance(msg, platform_message.Plain):
                text_parts.append(msg.text)
        return ''.join(text_parts).strip()

    async def send_reply(self, event_context: context.EventContext, text: str):
        """发送文本回复"""
        await event_context.reply(
            platform_message.MessageChain([
                platform_message.Plain(text=text)
            ])
        )

    async def search_pansou(self, keyword: str, cloud_types: Optional[List[str]] = None) -> List[Dict]:
        """
        调用 PanSou API 搜索网盘资源（支持 cloud_types 过滤）
        """
        api_url = f"{self.pansou_api_url.rstrip('/')}/api/search"

        payload = {
            "kw": keyword,
            "res": "merge"
        }
        if cloud_types is not None:
            payload["cloud_types"] = cloud_types

        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(
                    api_url,
                    json=payload,
                    headers={"Content-Type": "application/json"},
                    timeout=aiohttp.ClientTimeout(total=30)
                ) as response:
                    if response.status == 200:
                        data = await response.json()
                        return self.parse_search_results(data)
                    else:
                        return []
        except aiohttp.ClientError as e:
            return []
        except Exception as e:
            return []

    def parse_search_results(self, data: Dict) -> List[Dict]:
        """
        解析 PanSou API 返回的搜索结果
        """
        results = []

        # PanSou API 使用 res=merge 时，返回 merged_by_type 字段（按网盘类型分类）
        cloud_types = data.get("data", {}).get("merged_by_type", {})

        if isinstance(cloud_types, dict):
            for cloud_type, items in cloud_types.items():
                if not isinstance(items, list):
                    continue
                for item in items:
                    if len(results) >= self.count_limit:
                        break
                    result = self.format_result_item(item, cloud_type)
                    if result:
                        results.append(result)
                if len(results) >= self.count_limit:
                    break
        elif isinstance(cloud_types, list):
            # 如果直接返回列表格式
            for item in cloud_types:
                if len(results) >= self.count_limit:
                    break
                result = self.format_result_item(item, "unknown")
                if result:
                    results.append(result)

        return results

    def format_result_item(self, item: Dict, cloud_type: str) -> Optional[Dict]:
        """
        格式化单个搜索结果（适配 MergedLink 结构）
        """
        # MergedLink 结构: url, password, note, datetime, source, images
        # 获取标题（优先使用 note，兼容旧字段名）
        title = item.get("note") or item.get("title") or item.get("name") or item.get("text", "")
        if not title:
            return None

        # 获取链接
        link = item.get("url") or item.get("link") or ""

        # 获取密码
        password = item.get("password") or item.get("pwd") or ""

        # 获取来源
        source = item.get("source") or item.get("from") or item.get("channel") or ""

        # 获取时间并格式化
        time_str = item.get("datetime") or item.get("time") or item.get("date") or ""
        if time_str:
            try:
                import datetime
                if "T" in time_str:
                    if "+" in time_str:
                        time_str = time_str.split("+")[0]
                    elif "Z" in time_str:
                        time_str = time_str.replace("Z", "")
                    if "." in time_str:
                        time_str = time_str.split(".")[0]
                    dt = datetime.datetime.fromisoformat(time_str)
                    time_str = dt.strftime("%Y-%m-%d %H:%M:%S")
            except Exception:
                pass

        # 网盘类型映射
        cloud_type_names = {
            "baidu": "百度网盘",
            "aliyun": "阿里云盘",
            "quark": "夸克网盘",
            "tianyi": "天翼云盘",
            "uc": "UC网盘",
            "mobile": "移动云盘",
            "115": "115网盘",
            "pikpak": "PikPak",
            "xunlei": "迅雷网盘",
            "123": "123网盘",
            "magnet": "磁力链接",
            "ed2k": "电驴链接",
            "others": "其他",
        }

        cloud_name = cloud_type_names.get(cloud_type, cloud_type)

        # 获取图片
        images = item.get("images", [])

        return {
            "images": images,
            "title": title,
            "link": link,
            "password": password,
            "cloud_type": cloud_name,
            "source": source,
            "time": time_str
        }

    async def send_forward_results(
        self,
        event_context: context.EventContext,
        keyword: str,
        results: List[Dict]
    ):
        """
        使用合并转发消息发送搜索结果
        """
        # 构建消息列表
        messages = []

        for idx, result in enumerate(results, 1):
            # 构建单条消息内容
            content_text = f"【{idx}】{result['title']}\n"
            content_text += f"类型：{result['cloud_type']}\n"

            if result['link']:
                content_text += f"链接：{result['link']}\n"

            if result['password']:
                content_text += f"密码：{result['password']}\n"

            if result['source']:
                content_text += f"来源：{result['source']}\n"

            if result['time']:
                content_text += f"时间：{result['time']}"

            # 构建消息内容列表
            content = []
            
            # 先添加图片（如果有）
            if result.get("images") and isinstance(result["images"], list):
                for image_url in result["images"]:
                    if image_url:
                        content.append({"type": "image", "data": {"url": image_url}})
            
            # 再添加文本内容
            content.append({"type": "text", "data": {"text": content_text.strip()}})
            
            messages.append({"content": content})

        # 获取群号或用户ID
        event = event_context.event
        group_id = None
        user_id = None

        if hasattr(event, 'launcher_id'):
            if hasattr(event, 'launcher_type'):
                if event.launcher_type == 'group':
                    group_id = int(event.launcher_id)
                else:
                    user_id = int(event.launcher_id)

        # 尝试从其他属性获取
        if group_id is None and user_id is None:
            if hasattr(event, 'group_id'):
                group_id = int(event.group_id)
            elif hasattr(event, 'sender') and hasattr(event.sender, 'id'):
                user_id = int(event.sender.id)

        # 发送合并转发消息
        result = await self.forward_sender.send_forward(
            messages=messages,
            prompt=f"网盘搜索：{keyword}",
            summary=f"找到 {len(results)} 个结果",
            source="PanSou 网盘搜索",
            user_id="10000",
            nickname="网盘搜索助手",
            mode="multi",
            group_id=group_id,
            target_user_id=user_id
        )

        if not result.get("success"):
            # 如果合并转发失败，使用普通消息发送
            await self.send_plain_results(event_context, keyword, results)

    async def send_plain_results(
        self,
        event_context: context.EventContext,
        keyword: str,
        results: List[Dict]
    ):
        """
        使用普通消息发送搜索结果（作为合并转发失败的备选方案）
        """
        # 构建消息链
        message_chain = []
        
        # 添加标题
        message_chain.append(platform_message.Plain(text=f"网盘搜索：{keyword}\n"))
        message_chain.append(platform_message.Plain(text="━━━━━━━━━━━━━━━━\n"))

        for idx, result in enumerate(results, 1):
            # 添加结果文本
            result_text = f"\n【{idx}】{result['title']}\n"
            result_text += f" {result['cloud_type']}"

            if result['link']:
                result_text += f"\n {result['link']}"

            if result['password']:
                result_text += f"\n密码：{result['password']}"

            if result['source']:
                result_text += f"\n来源：{result['source']}"

            if result['time']:
                result_text += f"\n时间：{result['time']}"

            # 先添加图片（如果有）
            if result.get("images") and isinstance(result["images"], list):
                for image_url in result["images"]:
                    if image_url:
                        try:
                            # 添加图片消息
                            message_chain.append(platform_message.Image(url=image_url))
                        except Exception:
                            # 如果图片添加失败，忽略
                            pass

            result_text += "\n"
            message_chain.append(platform_message.Plain(text=result_text))

        # 添加结尾
        message_chain.append(platform_message.Plain(text=f"\n━━━━━━━━━━━━━━━━\n"))
        message_chain.append(platform_message.Plain(text=f"共找到 {len(results)} 个结果"))

        # 发送消息链
        await event_context.reply(
            platform_message.MessageChain(message_chain)
        )
